# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90589942c5f6b9a5aa94e03ec905e7cff8cc2444b29f645e17a995dc4070f6b4379eb80b277457a66c437764cf4d1d9e3bb5f6a73b395f90dcecef6255fc225c

test:
  secret_key_base: a7220f73536d4e7c34b910f234639f93685f580a337e301166471851a63d48f11eff935d40d4aa6b52dd9c03a16d2c486c0388651e009e5841d592bcaa11ced8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
